// Libro II. Generado por scratchpad\hacer_content.py sobre la produccion V6
// (out_v2, 15-sep-2026). Las duraciones estan medidas de cada mp3, no estimadas.
// Los interludios llevan label/badge: en la lista no dicen "Capitulo 101".
window.BOOK_DATA = {
  site: {
    saga: "El ciclo inmóvil",
    book: "Donde termina la luz",
    volume: "Libro II",
    author: "Escandar Giadach",
    audioBaseUrl: "audio/",
    audioVersion: 13,
    frontMatter: { title: "Presentación", kicker: "Antes de empezar", file: "00-donde-termina-la-luz.mp3", seconds: 7 }
  },
  // Retratos. "unlock" es el capitulo en el que el libro NOMBRA por primera vez
  // a ese personaje (verificado sobre el manuscrito V6): hasta llegar ahi la
  // tarjeta va bloqueada y ni el nombre ni la imagen entran en el HTML.
  // Las secciones agrupan las tarjetas por la faccion del canon. Una seccion
  // cuyos personajes siguen TODOS bloqueados no se pinta con su nombre: el
  // encabezado ("Dientes de Ceniza") ya seria el spoiler que se quiere evitar.
  castSections: [
    { id: "principales", name: "Personajes principales" },
    { id: "cam17", name: "CAM-17" },
    { id: "aurelian", name: "Aurelian", realm: "Fulgur" },
    { id: "gelidos", name: "Gélidos" },
    { id: "sevrin", name: "Sevrin", realm: "Fulgur" },
    { id: "helion", name: "Helion", realm: "Fulgur" },
    { id: "corven", name: "Corven", realm: "Fulgur" },
    { id: "ordel", name: "Ordel", realm: "Fulgur" },
    { id: "solenne", name: "Solenne", realm: "Fulgur" },
    { id: "ardent", name: "Ardent", realm: "Assum" },
    { id: "sareth", name: "Sareth", realm: "Assum" },
    { id: "draevin", name: "Draevin", realm: "Fulgur" },
    { id: "veyron", name: "Veyron", realm: "Fulgur" },
    { id: "veyra", name: "Veyra", realm: "Gélidos" },
    { id: "korr", name: "Korr", realm: "Gélidos" },
    { id: "noche", name: "La noche eterna" },
    { id: "dia", name: "El día eterno" },
    { id: "fulgur", name: "Fulgur" },
    { id: "assum", name: "Assum" }
  ],
  // Retratos de grupo: una sola imagen ancha que se abre en grande, con los
  // nombres al pie. Mismo bloqueo por capitulo que los retratos sueltos.
  groups: [
    { id: "corvenh", name: "Odran y Levik Corven", file: "assets/personajes/corven-hermanos.webp", w: 1800, h: 1350, unlock: 29, section: "corven",
      caption: "Odran Corven · Levik Corven" },
    { id: "solenneh", name: "Rhoven y Orielle Solenne", file: "assets/personajes/rhoven-orielle.webp", w: 1800, h: 1200, unlock: 29, section: "solenne",
      caption: "Rhoven Solenne · Orielle Solenne" },
    { id: "madres", name: "Las dos madres", file: "assets/personajes/las-dos-madres.webp", w: 1600, h: 1431, unlock: 36, section: "dia",
      caption: "Maelis Varen · Ilyra Aurelian" },
    { id: "dientes", name: "Dientes de Ceniza", file: "assets/personajes/dientes-de-ceniza.webp", w: 2400, h: 1200, unlock: 30, section: "dia",
      caption: "Hal'Verkan · Dra'Vik · Rask · Bryn'Veth · Tor'Vaer · Yorn'Taz" }
  ],
  // Escenas de capitulo (28-sep): solo en el orden por capitulo, como cabecera
  // del bloque. Los retratos sueltos muestran a cada personaje ya avanzado el
  // libro; estas lo muestran como esta en ESE capitulo. Se ven al terminarlo.
  chapterArt: [
    { chapter: 1, name: "La grabación de Gael", file: "assets/capitulos/cap01-01-la-grabacion-de-gael.webp", w: 1536, h: 1024 },
    { chapter: 1, name: "El muro de los nombres", file: "assets/capitulos/cap01-02-el-muro-de-los-nombres.webp", w: 1536, h: 1024 },
    { chapter: 1, name: "Elian en retención de seguridad", file: "assets/capitulos/cap01-03-elian-en-retencion-de-seguridad-v3.webp", w: 1536, h: 1024 },
    { chapter: 1, name: "Kier apaga el heroico rescate", file: "assets/capitulos/cap01-04-kier-apaga-el-heroico-rescate-v2.webp", w: 1536, h: 1024 },
    { chapter: 2, name: "El poder no responde", file: "assets/capitulos/cap02-02-el-poder-no-responde-v2.webp", w: 1536, h: 1024 },
    { chapter: 2, name: "Lucan en la pantalla de la celda", file: "assets/capitulos/cap02-03-lucan-en-la-pantalla-de-la-celda-v4.webp", w: 1536, h: 1024 },
    { chapter: 2, name: "La visita de Elías Sevrin", file: "assets/capitulos/cap02-04-la-visita-de-elias-sevrin-v3.webp", w: 1536, h: 1024 },
    { chapter: 2, name: "Elian", file: "assets/capitulos/cap02-elian.webp", w: 1374, h: 1145 },
    { chapter: 3, name: "Ansel y Neris en la estación olvidada", file: "assets/capitulos/cap03-01-ansel-y-neris-en-la-estacion-olvidada.webp", w: 1536, h: 1024 },
    { chapter: 3, name: "Sava en la estación de bombeo", file: "assets/capitulos/cap03-02-sava-en-la-estacion-de-bombeo.webp", w: 1536, h: 1024 },
    { chapter: 3, name: "Lucan contra Varek", file: "assets/capitulos/cap03-03-lucan-contra-varek.webp", w: 1536, h: 1024 },
    { chapter: 3, name: "Neris desarma el anclaje", file: "assets/capitulos/cap03-04-neris-desarma-el-anclaje.webp", w: 1536, h: 1024 },
    { chapter: 4, name: "Las Casas vienen por los graduados", file: "assets/capitulos/cap04-01-las-casas-vienen-por-los-graduados-v4.webp", w: 1536, h: 1024 },
    { chapter: 4, name: "La noticia de Rhel", file: "assets/capitulos/cap04-02-la-noticia-de-rhel-v3.webp", w: 1536, h: 1024 },
    { chapter: 4, name: "Los cuatro expedientes", file: "assets/capitulos/cap04-03-los-cuatro-expedientes-v2.webp", w: 1536, h: 1024 },
    { chapter: 5, name: "Elías vuelve a la celda", file: "assets/capitulos/cap05-01-elias-vuelve-a-la-celda-v2.webp", w: 1536, h: 1024 },
    { chapter: 5, name: "La primera capa de hielo", file: "assets/capitulos/cap05-02-la-primera-capa-de-hielo.webp", w: 1536, h: 1024 },
    { chapter: 5, name: "La prótesis fea y funcional", file: "assets/capitulos/cap05-03-la-protesis-fea-y-funcional.webp", w: 1536, h: 1024 },
    { chapter: 6, name: "El puente de hielo", file: "assets/capitulos/cap06-01-el-puente-de-hielo-v2.webp", w: 1536, h: 1024 },
    { chapter: 6, name: "La lanza contra cinco máquinas", file: "assets/capitulos/cap06-02-la-lanza-contra-cinco-maquinas-v2.webp", w: 1536, h: 1024 },
    { chapter: 6, name: "La banca frente a la puerta Sevrin", file: "assets/capitulos/cap06-03-la-banca-frente-a-la-puerta-sevrin-v2.webp", w: 1536, h: 1024 },
    { chapter: 6, name: "Kier firma con Helion", file: "assets/capitulos/cap06-04-kier-firma-con-helion-v3.webp", w: 1536, h: 1024 },
    { chapter: 6, name: "Sujeto ST-17", file: "assets/capitulos/cap06-05-sujeto-st-17-v3.webp", w: 1536, h: 1024 },
    { chapter: 7, name: "Dos rescates en el mismo corredor", file: "assets/capitulos/cap07-03-dos-rescates-en-el-mismo-corredor-v2.webp", w: 1536, h: 1024 },
    { chapter: 7, name: "El abrazo a Ansel", file: "assets/capitulos/cap07-04-el-abrazo-a-ansel-v2.webp", w: 1536, h: 1024 },
    { chapter: 7, name: "Lucan sale de la oscuridad", file: "assets/capitulos/cap07-05-lucan-sale-de-la-oscuridad-v2.webp", w: 1536, h: 1024 },
    { chapter: 8, name: "La espada de Ansel y la ráfaga de Neris", file: "assets/capitulos/cap08-02-la-espada-de-ansel-y-la-rafaga-de-neris-v4.webp", w: 1536, h: 1024 },
    { chapter: 8, name: "Neris se vuelve cristal", file: "assets/capitulos/cap08-04-neris-se-vuelve-cristal-v4.webp", w: 1536, h: 1024 },
    { chapter: 8, name: "Ansel murió", file: "assets/capitulos/cap08-05-ansel-murio.webp", w: 1536, h: 1024 },
    { chapter: 9, name: "Lina gana el combate", file: "assets/capitulos/cap09-02-lina-gana-el-combate-v4.webp", w: 1536, h: 1024 },
    { chapter: 9, name: "Guardia bajo las estrellas", file: "assets/capitulos/cap09-03-guardia-bajo-las-estrellas.webp", w: 1536, h: 1024 },
    { chapter: 9, name: "El anciano y el ángel", file: "assets/capitulos/cap09-04-el-anciano-y-el-angel-v2.webp", w: 1536, h: 1024 },
    { chapter: 10, name: "Kier derrite la compuerta", file: "assets/capitulos/cap10-01-kier-derrite-la-compuerta-v2.webp", w: 1536, h: 1024 },
    { chapter: 10, name: "El pozo central de A-7", file: "assets/capitulos/cap10-02-el-pozo-central-de-a-7.webp", w: 1536, h: 1024 },
    { chapter: 10, name: "Los archivos de la convergencia", file: "assets/capitulos/cap10-03-los-archivos-de-la-convergencia-v3.webp", w: 1536, h: 1024 },
    { chapter: 11, name: "Sevrin toma A-7", file: "assets/capitulos/cap11-01-sevrin-toma-a-7-v4.webp", w: 1536, h: 1024 },
    { chapter: 11, name: "Delyan paraliza a Kier", file: "assets/capitulos/cap11-02-delyan-paraliza-a-kier-v2.webp", w: 1536, h: 1024 },
    { chapter: 11, name: "La Corona de Nidum: junto al Prime", file: "assets/capitulos/cap11-05-la-corona-de-nidum-junto-al-prime-v2.webp", w: 1536, h: 1024 },
    { chapter: 12, name: "La Corona de día y la Mesa de Custodia", file: "assets/capitulos/cap12-01-la-corona-de-dia-y-la-mesa-de-custodia-v3.webp", w: 1536, h: 1024 },
    { chapter: 12, name: "Coris Korr contra Yvara Sareth", file: "assets/capitulos/cap12-03-coris-korr-contra-yvara-sareth.webp", w: 1536, h: 1024 },
    { chapter: 13, name: "Nhalia Veyra, vendada, contra Zane Veyron", file: "assets/capitulos/cap13-01-nhalia-veyra-vendada-contra-zane-veyron.webp", w: 1536, h: 1024 },
    { chapter: 14, name: "Lina en el palco Aurelian; Rivan se sienta a su lado", file: "assets/capitulos/cap14-01-lina-en-el-palco-aurelian-rivan-se-sient.webp", w: 1536, h: 1024 },
    { chapter: 14, name: "Mara visita a Lina", file: "assets/capitulos/cap14-03-mara-visita-a-lina.webp", w: 1536, h: 1024 },
    { chapter: 14, name: "Visita a Kier en la custodia Sevrin", file: "assets/capitulos/cap14-04-visita-a-kier-en-la-custodia-sevrin-v3.webp", w: 1536, h: 1024 },
    { chapter: 15, name: "Hacia el oeste bajo las auroras", file: "assets/capitulos/cap15-01-hacia-el-oeste-bajo-las-auroras.webp", w: 1536, h: 1024 },
    { chapter: 15, name: "El cuchillo torcido de Ian", file: "assets/capitulos/cap15-02-el-cuchillo-torcido-de-ian-v2.webp", w: 1536, h: 1024 },
    { chapter: 15, name: "Cristales rojos en la nieve", file: "assets/capitulos/cap15-03-cristales-rojos-en-la-nieve-v4.webp", w: 1536, h: 1024 },
    { chapter: 15, name: "Las ruinas en la montaña y los ojos rojos", file: "assets/capitulos/cap15-04-las-ruinas-en-la-montana-y-los-ojos-rojo-v2.webp", w: 1536, h: 1024 },
    { chapter: 16, name: "Scar sale del refugio y lanza Hielo Rojo", file: "assets/capitulos/cap16-01-scar-sale-del-refugio-y-lanza-hielo-rojo-v2.webp", w: 1536, h: 1024 },
    { chapter: 16, name: "Derrota frente a Scar", file: "assets/capitulos/cap16-02-derrota-frente-a-scar.webp", w: 1536, h: 1024 },
    { chapter: 16, name: "Atados junto a la fogata", file: "assets/capitulos/cap16-03-atados-junto-a-la-fogata.webp", w: 1536, h: 1024 },
    { chapter: 16, name: "“Eres un híbrido”: Scar", file: "assets/capitulos/cap16-04-eres-un-hibrido-scar.webp", w: 1536, h: 1024 },
    { chapter: 17, name: "El Archivo Genealógico: SEVRIN", file: "assets/capitulos/cap17-01-el-archivo-genealogico-sevrin.webp", w: 1536, h: 1024 },
    { chapter: 19, name: "El orbe contra Elías y Duvran", file: "assets/capitulos/cap19-01-el-orbe-contra-elias-y-duvran.webp", w: 1536, h: 1024 },
    { chapter: 19, name: "La sala de contingencias de Nethar", file: "assets/capitulos/cap19-02-la-sala-de-contingencias-de-nethar-v2.webp", w: 1536, h: 1024 },
    { chapter: 20, name: "El taller Draevin", file: "assets/capitulos/cap20-01-el-taller-draevin.webp", w: 1536, h: 1024 },
    { chapter: 20, name: "El orbe ante los Draevin: la cuchilla de Selq", file: "assets/capitulos/cap20-02-el-orbe-ante-los-draevin-la-cuchilla-de.webp", w: 1536, h: 1024 },
    { chapter: 20, name: "Las botas congeladas de Elías", file: "assets/capitulos/cap20-03-las-botas-congeladas-de-elias.webp", w: 1536, h: 1024 },
    { chapter: 20, name: "La estación de carga", file: "assets/capitulos/cap20-04-la-estacion-de-carga.webp", w: 1536, h: 1024 },
    { chapter: 20, name: "El beso de Zaira", file: "assets/capitulos/cap20-05-el-beso-de-zaira.webp", w: 1536, h: 1024 },
    { chapter: 21, name: "El entrenamiento empieza con una piedra", file: "assets/capitulos/cap21-01-el-entrenamiento-empieza-con-una-piedra.webp", w: 1536, h: 1024 },
    { chapter: 21, name: "La espada de Hielo Rojo se fractura", file: "assets/capitulos/cap21-02-la-espada-de-hielo-rojo-se-fractura-v3.webp", w: 1536, h: 1024 },
    { chapter: 21, name: "Cena en el refugio y la espada de Scar", file: "assets/capitulos/cap21-04-cena-en-el-refugio-y-la-espada-de-scar.webp", w: 1536, h: 1024 },
    { chapter: 23, name: "La comida quemada", file: "assets/capitulos/cap23-02-la-comida-quemada.webp", w: 1536, h: 1024 },
    { chapter: 23, name: "El collar de Hielo Negro", file: "assets/capitulos/cap23-03-el-collar-de-hielo-negro-v2.webp", w: 1536, h: 1024 },
    { chapter: 23, name: "Scar dice su nombre: Keireth Vaelor", file: "assets/capitulos/cap23-04-scar-dice-su-nombre-keireth-vaelor-v2.webp", w: 1536, h: 1024 },
    { chapter: 24, name: "El tren de Solenne baja por la cara exterior del Muro", file: "assets/capitulos/cap24-01-el-tren-de-solenne-baja-por-la-cara-exte.webp", w: 1536, h: 1024 },
    { chapter: 24, name: "Comida picante al borde de la plataforma", file: "assets/capitulos/cap24-02-comida-picante-al-borde-de-la-plataforma.webp", w: 1536, h: 1024 },
    { chapter: 25, name: "Emboscada y vuelco del vehículo", file: "assets/capitulos/cap25-01-emboscada-y-vuelco-del-vehiculo.webp", w: 1536, h: 1024 },
    { chapter: 25, name: "Kier arranca la puerta y la lanza mata a Calev", file: "assets/capitulos/cap25-02-kier-arranca-la-puerta-y-la-lanza-mata-a-v2.webp", w: 1536, h: 1024 },
    { chapter: 25, name: "Pelea contra los Dientes de Ceniza", file: "assets/capitulos/cap25-03-pelea-contra-los-dientes-de-ceniza.webp", w: 1536, h: 1024 },
    { chapter: 25, name: "Atrapados en las redes al rojo", file: "assets/capitulos/cap25-05-atrapados-en-las-redes-al-rojo-v2.webp", w: 1536, h: 1024 },
    { chapter: 26, name: "Aprender a caminar y el empujón", file: "assets/capitulos/cap26-02-aprender-a-caminar-y-el-empujon.webp", w: 1536, h: 1024 },
    { chapter: 26, name: "El número 17 en la pared", file: "assets/capitulos/cap26-03-el-numero-17-en-la-pared.webp", w: 1536, h: 1024 },
    { chapter: 26, name: "Arlette se reconoce en el espejo", file: "assets/capitulos/cap26-05-arlette-se-reconoce-en-el-espejo.webp", w: 1536, h: 1024 },
    { chapter: 27, name: "Llegada al asentamiento de los Dientes", file: "assets/capitulos/cap27-01-llegada-al-asentamiento-de-los-dientes-v2.webp", w: 1536, h: 1024 },
    { chapter: 27, name: "«Hibridación»: la mentira ante Rask", file: "assets/capitulos/cap27-03-hibridacion-la-mentira-ante-rask.webp", w: 1536, h: 1024 },
    { chapter: 28, name: "Último mapa en el refugio", file: "assets/capitulos/cap28-01-ultimo-mapa-en-el-refugio-v2.webp", w: 1536, h: 1024 },
    { chapter: 28, name: "Los abrazos en la elevación de roca", file: "assets/capitulos/cap28-02-los-abrazos-en-la-elevacion-de-roca-v2.webp", w: 1536, h: 1024 },
    { chapter: 28, name: "Bajo la costra del segundo valle", file: "assets/capitulos/cap28-03-bajo-la-costra-del-segundo-valle-v2.webp", w: 1536, h: 1024 },
    { chapter: 28, name: "Sombras bajo el hielo y criaturas del vapor", file: "assets/capitulos/cap28-04-sombras-bajo-el-hielo-y-criaturas-del-va.webp", w: 1536, h: 1024 },
    { chapter: 28, name: "Huellas de botas alrededor de la grieta", file: "assets/capitulos/cap28-05-huellas-de-botas-alrededor-de-la-grieta.webp", w: 1536, h: 1024 },
    { chapter: 29, name: "La cifra de muertos en la pared y la mesa de las Casas", file: "assets/capitulos/cap29-01-la-cifra-de-muertos-en-la-pared-y-la-mes.webp", w: 1536, h: 1024 },
    { chapter: 29, name: "Varya Helion acusa a Aurelian", file: "assets/capitulos/cap29-02-varya-helion-acusa-a-aurelian.webp", w: 1536, h: 1024 },
    { chapter: 29, name: "Tomas Eiden en la terraza sobre el tráfico del Muro", file: "assets/capitulos/cap29-03-tomas-eiden-en-la-terraza-sobre-el-trafi.webp", w: 1536, h: 1024 },
    { chapter: 29, name: "Kael Ardent y Koren en la baranda", file: "assets/capitulos/cap29-04-kael-ardent-y-koren-en-la-baranda-v2.webp", w: 1536, h: 1024 },
    { chapter: 101, name: "El cuarto recipiente negado", file: "assets/capitulos/cap101-01-el-cuarto-recipiente-negado.webp", w: 1536, h: 1024 },
    { chapter: 101, name: "Zapatos a cambio de agua", file: "assets/capitulos/cap101-02-zapatos-a-cambio-de-agua.webp", w: 1536, h: 1024 },
    { chapter: 30, name: "Kier ayuda a levantar una placa del convoy", file: "assets/capitulos/cap30-01-kier-ayuda-a-levantar-una-placa-del-conv.webp", w: 1536, h: 1024 },
    { chapter: 30, name: "La pelea con los cuatro asaltantes", file: "assets/capitulos/cap30-03-la-pelea-con-los-cuatro-asaltantes-v2.webp", w: 1536, h: 1024 },
    { chapter: 30, name: "Bryn'Veth y las correas de la maza", file: "assets/capitulos/cap30-04-bryn-veth-y-las-correas-de-la-maza-v2.webp", w: 1536, h: 1024 },
    { chapter: 30, name: "Rask le ofrece quedarse", file: "assets/capitulos/cap30-05-rask-le-ofrece-quedarse-v2.webp", w: 1536, h: 1024 },
    { chapter: 32, name: "Fuego del Assum contra el muro de hielo", file: "assets/capitulos/cap32-02-fuego-del-assum-contra-el-muro-de-hielo.webp", w: 1536, h: 1024 },
    { chapter: 32, name: "Dejar llegar la transferencia al cien por ciento", file: "assets/capitulos/cap32-03-dejar-llegar-la-transferencia-al-cien-po.webp", w: 1536, h: 1024 },
    { chapter: 32, name: "El muchacho del brazo congelado", file: "assets/capitulos/cap32-04-el-muchacho-del-brazo-congelado.webp", w: 1536, h: 1024 },
    { chapter: 32, name: "Rivan Aurelian anota dos nombres", file: "assets/capitulos/cap32-05-rivan-aurelian-anota-dos-nombres.webp", w: 1536, h: 1024 },
    { chapter: 33, name: "Emboscada junto al vehículo destruido", file: "assets/capitulos/cap33-02-emboscada-junto-al-vehiculo-destruido.webp", w: 1536, h: 1024 },
    { chapter: 33, name: "Kier escucha la discusión sobre él", file: "assets/capitulos/cap33-03-kier-escucha-la-discusion-sobre-el.webp", w: 1536, h: 1024 },
    { chapter: 33, name: "El laboratorio a la vista", file: "assets/capitulos/cap33-04-el-laboratorio-a-la-vista.webp", w: 1536, h: 1024 },
    { chapter: 35, name: "Rivan espía la reunión en el depósito", file: "assets/capitulos/cap35-01-rivan-espia-la-reunion-en-el-deposito.webp", w: 1536, h: 1024 },
    { chapter: 35, name: "La entrega en la compuerta y la llamada de Mara", file: "assets/capitulos/cap35-02-la-entrega-en-la-compuerta-y-la-llamada.webp", w: 1536, h: 1024 },
    { chapter: 36, name: "Las pantallas y la puerta que reconoce a Lina", file: "assets/capitulos/cap36-01-las-pantallas-y-la-puerta-que-reconoce-a.webp", w: 1536, h: 1024 },
    { chapter: 36, name: "Ilyra detrás del vidrio", file: "assets/capitulos/cap36-02-ilyra-detras-del-vidrio.webp", w: 1536, h: 1024 },
    { chapter: 36, name: "Hal envía el mensaje", file: "assets/capitulos/cap36-05-hal-envia-el-mensaje.webp", w: 1536, h: 1024 },
    { chapter: 38, name: "Rask descubre el mensaje", file: "assets/capitulos/cap38-01-rask-descubre-el-mensaje.webp", w: 1536, h: 1024 },
    { chapter: 38, name: "La puñalada en la oscuridad", file: "assets/capitulos/cap38-02-la-punalada-en-la-oscuridad.webp", w: 1536, h: 1024 },
    { chapter: 38, name: "Las últimas órdenes de Rask", file: "assets/capitulos/cap38-03-las-ultimas-ordenes-de-rask.webp", w: 1536, h: 1024 },
    { chapter: 38, name: "Kier contra Hal y la muerte de Rask", file: "assets/capitulos/cap38-04-kier-contra-hal-y-la-muerte-de-rask.webp", w: 1536, h: 1024 },
    { chapter: 39, name: "Mara y Rivan caen sobre el laboratorio", file: "assets/capitulos/cap39-01-mara-y-rivan-caen-sobre-el-laboratorio.webp", w: 1536, h: 1024 },
    { chapter: 39, name: "Rivan mata a Tor y a Dra'Vik", file: "assets/capitulos/cap39-02-rivan-mata-a-tor-y-a-dra-vik.webp", w: 1536, h: 1024 },
    { chapter: 39, name: "La despedida en el conducto", file: "assets/capitulos/cap39-04-la-despedida-en-el-conducto.webp", w: 1536, h: 1024 },
    { chapter: 39, name: "Salida al Sol Eterno y la piedra marcada", file: "assets/capitulos/cap39-05-salida-al-sol-eterno-y-la-piedra-marcada.webp", w: 1536, h: 1024 },
    { chapter: 40, name: "Rivan y Selq en el bar", file: "assets/capitulos/cap40-01-rivan-y-selq-en-el-bar.webp", w: 1536, h: 1024 },
    { chapter: 40, name: "Sabotaje, emboscada e interrogatorio", file: "assets/capitulos/cap40-02-sabotaje-emboscada-e-interrogatorio.webp", w: 1536, h: 1024 },
    { chapter: 42, name: "Bajo los árboles: la culpa de Kier", file: "assets/capitulos/cap42-01-bajo-los-arboles-la-culpa-de-kier.webp", w: 1536, h: 1024 }
  ],
  characters: [
    { id: "gael", name: "Gael Altaren", file: "assets/personajes/gael-altaren.webp", w: 900, h: 1350, unlock: 1, section: "cam17" },
    { id: "ian", name: "Ian de Vries", file: "assets/personajes/ian-de-vries.webp", w: 900, h: 1350, unlock: 1, section: "principales" },
    { id: "elian", name: "Elian Nahl", file: "assets/personajes/elian-nahl.webp", w: 900, h: 1350, unlock: 1, section: "principales" },
    { id: "kier", name: "Kier de Vries", file: "assets/personajes/kier-de-vries.webp", w: 900, h: 1351, unlock: 1, section: "principales" },
    { id: "lina", name: "Lina Aurelian", file: "assets/personajes/lina-aurelian.webp", w: 900, h: 1348, unlock: 1, section: "principales" },
    { id: "daren", name: "Daren de Vries", file: "assets/personajes/daren-de-vries.webp", w: 900, h: 1350, unlock: 1, section: "principales" },
    { id: "elias", name: "Elías Sevrin", file: "assets/personajes/elias-sevrin.webp", w: 900, h: 1350, unlock: 2, section: "principales" },
    { id: "ansel", name: "Ansel Nahl", file: "assets/personajes/ansel-nahl.webp", w: 900, h: 1350, unlock: 2, section: "gelidos" },
    { id: "sava", name: "Sava", file: "assets/personajes/sava.webp", w: 900, h: 1350, unlock: 2, section: "gelidos" },
    { id: "neris", name: "Neris", file: "assets/personajes/neris.webp", w: 900, h: 1350, unlock: 3, section: "gelidos" },
    { id: "jun", name: "Jun Arven", file: "assets/personajes/jun-arven.webp", w: 900, h: 1350, unlock: 4, section: "cam17" },
    { id: "tomas", name: "Tomas Eiden", file: "assets/personajes/tomas-eiden.webp", w: 900, h: 1350, unlock: 4, section: "cam17" },
    { id: "vera", name: "Vera Helion", file: "assets/personajes/vera-helion.webp", w: 900, h: 1350, unlock: 4, section: "cam17" },
    { id: "nila", name: "Nila Sorn", file: "assets/personajes/nila-sorn.webp", w: 900, h: 1350, unlock: 4, section: "cam17" },
    { id: "iris", name: "Iris Veyra", file: "assets/personajes/iris-veyra.webp", w: 900, h: 1350, unlock: 4, section: "cam17" },
    { id: "scar", name: "Scar", file: "assets/personajes/scar.webp", w: 900, h: 1350, unlock: 16, section: "noche" },
    { id: "arlette", name: "Arlette Voss", file: "assets/personajes/arlette-voss.webp", w: 900, h: 1350, unlock: 26, section: "cam17" },
    { id: "maelis", name: "Maelis Varen", file: "assets/personajes/maelis-varen.webp", w: 900, h: 1350, unlock: 36, section: "dia" },
    { id: "lucan", name: "Lucan Aurelian", file: "assets/personajes/lucan-aurelian.webp", w: 900, h: 1350, unlock: 1, section: "aurelian" },
    { id: "adrian", name: "Adrian Aurelian", file: "assets/personajes/adrian-aurelian.webp", w: 900, h: 1350, unlock: 4, section: "aurelian" },
    { id: "mara", name: "Mara Aurelian", file: "assets/personajes/mara-aurelian.webp", w: 900, h: 1350, unlock: 14, section: "aurelian" },
    { id: "edria", name: "Edria Aurelian", file: "assets/personajes/edria-aurelian.webp", w: 900, h: 1350, unlock: 13, section: "aurelian" },
    { id: "ilyra", name: "Ilyra Aurelian", file: "assets/personajes/ilyra-aurelian.webp", w: 900, h: 1350, unlock: 36, section: "dia" },
    { id: "rivan", name: "Rivan Aurelian", file: "assets/personajes/rivan-aurelian.webp", w: 900, h: 1350, unlock: 14, section: "aurelian" },
    { id: "tavian", name: "Tavian Aurelian", file: "assets/personajes/tavian-aurelian.webp", w: 900, h: 1350, unlock: 14, section: "aurelian" },
    { id: "aedra", name: "Aedra Draevin", file: "assets/personajes/aedra-draevin.webp", w: 900, h: 1350, unlock: 20, section: "draevin" },
    { id: "selq", name: "Selq", file: "assets/personajes/selq.webp", w: 900, h: 1350, unlock: 20, section: "draevin" },
    { id: "khara", name: "Khara", file: "assets/personajes/khara.webp", w: 900, h: 1350, unlock: 20, section: "draevin" },
    { id: "cassian", name: "Cassian Sevrin", file: "assets/personajes/cassian-sevrin.webp", w: 900, h: 1350, unlock: 11, section: "sevrin" },
    { id: "nethar", name: "Nethar Sevrin", file: "assets/personajes/nethar-sevrin.webp", w: 900, h: 1350, unlock: 11, section: "sevrin" },
    { id: "duvran", name: "Duvran Sevrin", file: "assets/personajes/duvran-sevrin.webp", w: 900, h: 1350, unlock: 11, section: "sevrin" },
    { id: "delyan", name: "Delyan", file: "assets/personajes/delyan.webp", w: 900, h: 1350, unlock: 11, section: "sevrin" },
    { id: "damar", name: "Damar Veyron", file: "assets/personajes/damar-veyron.webp", w: 900, h: 1350, unlock: 29, section: "veyron" },
    { id: "nhyr", name: "Nhyr Ordel", file: "assets/personajes/nhyr-ordel.webp", w: 900, h: 1350, unlock: 29, section: "ordel" },
    { id: "coris", name: "Coris", file: "assets/personajes/coris.webp", w: 900, h: 1350, unlock: 12, section: "korr" },
    { id: "nhalia", name: "Nhalia Veyra", file: "assets/personajes/nhalia-veyra.webp", w: 900, h: 1350, unlock: 13, section: "veyra" },
    { id: "loras", name: "Loras Corven", file: "assets/personajes/loras-corven.webp", w: 900, h: 1350, unlock: 12, section: "corven" },
    { id: "averian", name: "Averian Vaelor", file: "assets/personajes/averian-vaelor.webp", w: 900, h: 1350, unlock: 23, section: "noche" },
    { id: "zane", name: "Zane Veyron", file: "assets/personajes/zane-veyron.webp", w: 900, h: 1350, unlock: 13, section: "veyron" },
    { id: "ysven", name: "Ysven Veyron", file: "assets/personajes/ysven-veyron.webp", w: 900, h: 1350, unlock: 13, section: "veyron" },
    { id: "solvar", name: "Solvar Helion", file: "assets/personajes/solvar-helion.webp", w: 900, h: 1350, unlock: 13, section: "helion" },
    { id: "varya", name: "Varya Helion", file: "assets/personajes/varya-helion.webp", w: 900, h: 1350, unlock: 29, section: "helion" },
    { id: "zaira", name: "Zaira", file: "assets/personajes/zaira.webp", w: 900, h: 1349, unlock: 20, section: "draevin" },
    { id: "nara", name: "Nara", file: "assets/personajes/nara.webp", w: 900, h: 1350, unlock: 24, section: "aurelian" },
    { id: "calev", name: "Calev", file: "assets/personajes/calev.webp", w: 900, h: 1350, unlock: 24, section: "aurelian" },
    { id: "aldren", name: "Aldren Soryn", epithet: "El Heredero de la Luna Bélica", file: "assets/personajes/aldren-soryn.webp", w: 900, h: 1350, unlock: 23, section: "noche" },
    { id: "yseva", name: "Yseva Soryn", epithet: "La Astrónoma de la Guerra", file: "assets/personajes/yseva-soryn.webp", w: 900, h: 1350, unlock: 31, section: "noche" },
    { id: "hastir", name: "Hastir Soryn", epithet: "La Garra Carmesí", file: "assets/personajes/hastir-soryn.webp", w: 900, h: 1350, unlock: 31, section: "noche" },
    { id: "yvara", name: "Yvara", file: "assets/personajes/yvara.webp", w: 900, h: 1350, unlock: 12, section: "sareth" },
    { id: "kaedrahn", name: "Kaedrahn", file: "assets/personajes/kaedrahn.webp", w: 900, h: 1350, unlock: 12, section: "ardent" },
    { id: "rask", name: "Rask", file: "assets/personajes/rask.webp", w: 900, h: 1350, unlock: 25, section: "dia" },
    { id: "hal", name: "Hal'Verkan", file: "assets/personajes/hal-verkan.webp", w: 900, h: 1350, unlock: 30, section: "dia" },
    { id: "dravik", name: "Dra'Vik", file: "assets/personajes/dravik.webp", w: 900, h: 1350, unlock: 30, section: "dia" },
    { id: "bryn", name: "Bryn'Veth", file: "assets/personajes/bryn-veth.webp", w: 900, h: 1350, unlock: 30, section: "dia" },
    { id: "tor", name: "Tor'Vaer", file: "assets/personajes/tor-vaer.webp", w: 900, h: 1350, unlock: 30, section: "dia" },
    { id: "yorn", name: "Yorn'Taz", file: "assets/personajes/yorn-taz.webp", w: 900, h: 1350, unlock: 30, section: "dia" }
  ],
  // Escenas en bucle. Son mp4 MUDOS, no gif: el mismo clip en gif pesaba
  // 30 MB y en mp4 1,8. Se pausan mientras suena el audiolibro.
  scenes: [
    { id: "delyan", name: "Delyan", file: "assets/escenas/delyan-combate.mp4", poster: "assets/escenas/delyan-combate.webp", w: 900, h: 506, unlock: 11, caption: "Guardia de élite de Casa Sevrin" }
  ],
  chapters: [
    { number: 1, title: "El héroe de CAM-17", part: "Parte I", file: "01-el-heroe-de-cam-17.mp3", seconds: 2349 },
    { number: 2, title: "Memoria de hielo", part: "Parte I", file: "02-memoria-de-hielo.mp3", seconds: 1354 },
    { number: 3, title: "Una cosa a la vez", part: "Parte I", file: "03-una-cosa-a-la-vez.mp3", seconds: 1834 },
    { number: 4, title: "Bajo custodia", part: "Parte I", file: "04-bajo-custodia.mp3", seconds: 2703 },
    { number: 5, title: "Rutas de salida", part: "Parte I", file: "05-rutas-de-salida.mp3", seconds: 2281 },
    { number: 6, title: "Antes que termine el día", part: "Parte I", file: "06-antes-que-termine-el-dia.mp3", seconds: 2729 },
    { number: 7, title: "El rescate", part: "Parte I", file: "07-el-rescate.mp3", seconds: 2513 },
    { number: 8, title: "Demasiado fuerte", part: "Parte I", file: "08-demasiado-fuerte.mp3", seconds: 1295 },
    { number: 9, title: "Del otro lado del Muro", part: "Parte II", file: "09-del-otro-lado-del-muro.mp3", seconds: 3505 },
    { number: 10, title: "El laboratorio", part: "Parte II", file: "10-el-laboratorio.mp3", seconds: 3031 },
    { number: 11, title: "Bayas de escarcha", part: "Parte II", file: "11-bayas-de-escarcha.mp3", seconds: 2802 },
    { number: 12, title: "Casi como en casa", part: "Parte II", file: "12-casi-como-en-casa.mp3", seconds: 1530 },
    { number: 13, title: "Derrotas", part: "Parte II", file: "13-derrotas.mp3", seconds: 1857 },
    { number: 14, title: "El Rojo", part: "Parte II", file: "14-el-rojo.mp3", seconds: 2353 },
    { number: 15, title: "Donde termina el mapa", part: "Parte II", file: "15-donde-termina-el-mapa.mp3", seconds: 1804 },
    { number: 16, title: "Hielo Rojo", part: "Parte II", file: "16-hielo-rojo.mp3", seconds: 1469 },
    { number: 17, title: "El apellido", part: "Parte III", file: "17-el-apellido.mp3", seconds: 1350 },
    { number: 18, title: "Bienvenida a la familia", part: "Parte III", file: "18-bienvenida-a-la-familia.mp3", seconds: 445 },
    { number: 19, title: "Contingencias", part: "Parte III", file: "19-contingencias.mp3", seconds: 1401 },
    { number: 20, title: "Trayectorias", part: "Parte III", file: "20-trayectorias.mp3", seconds: 1739 },
    { number: 21, title: "Lo que aprendieron", part: "Parte III", file: "21-lo-que-aprendieron.mp3", seconds: 1746 },
    { number: 22, title: "Reencuentro", part: "Parte III", file: "22-reencuentro.mp3", seconds: 974 },
    { number: 23, title: "Una fecha inventada", part: "Parte III", file: "23-una-fecha-inventada.mp3", seconds: 1757 },
    { number: 24, title: "Donde no anochece", part: "Parte III", file: "24-donde-no-anochece.mp3", seconds: 1930 },
    { number: 25, title: "Dientes de Ceniza", part: "Parte III", file: "25-dientes-de-ceniza.mp3", seconds: 2050 },
    { number: 26, title: "Debajo", part: "Parte III", file: "26-debajo.mp3", seconds: 1247 },
    { number: 27, title: "Bajo el sol eterno", part: "Parte IV", file: "27-bajo-el-sol-eterno.mp3", seconds: 1056 },
    { number: 28, title: "Hasta aquí", part: "Parte IV", file: "28-hasta-aqui.mp3", seconds: 1322 },
    { number: 29, title: "Cuarenta y siete", part: "Parte IV", file: "29-cuarenta-y-siete.mp3", seconds: 1541 },
    { number: 101, label: "Interludio I", badge: "I", title: "La ración", part: "Parte IV", file: "29b-interludio-i-la-racion.mp3", seconds: 142 },
    { number: 30, title: "Lo mejor de lo mejor", part: "Parte IV", file: "30-lo-mejor-de-lo-mejor.mp3", seconds: 1427 },
    { number: 31, title: "Los hermanos", part: "Parte IV", file: "31-los-hermanos.mp3", seconds: 1041 },
    { number: 32, title: "Daños colaterales", part: "Parte IV", file: "32-danos-colaterales.mp3", seconds: 1520 },
    { number: 33, title: "Nadie tiene que saberlo", part: "Parte IV", file: "33-nadie-tiene-que-saberlo.mp3", seconds: 2013 },
    { number: 34, title: "El Ángel", part: "Parte IV", file: "34-el-angel.mp3", seconds: 1389 },
    { number: 102, label: "Interludio II", badge: "II", title: "La entrada", part: "Parte IV", file: "34b-interludio-ii-la-entrada.mp3", seconds: 110 },
    { number: 35, title: "Huellas", part: "Parte IV", file: "35-huellas.mp3", seconds: 931 },
    { number: 36, title: "Las dos madres", part: "Parte IV", file: "36-las-dos-madres.mp3", seconds: 1944 },
    { number: 37, title: "Guerras de humanos", part: "Parte IV", file: "37-guerras-de-humanos.mp3", seconds: 1273 },
    { number: 38, title: "Por la espalda", part: "Parte IV", file: "38-por-la-espalda.mp3", seconds: 1837 },
    { number: 39, title: "¿Cuáles?", part: "Parte IV", file: "39-cuales.mp3", seconds: 2248 },
    { number: 103, label: "Interludio III", badge: "III", title: "Los nombres", part: "Parte IV", file: "39b-interludio-iii-los-nombres.mp3", seconds: 172 },
    { number: 40, title: "Demasiado importante", part: "Parte IV", file: "40-demasiado-importante.mp3", seconds: 2883 },
    { number: 41, title: "Sin retorno", part: "Parte IV", file: "41-sin-retorno.mp3", seconds: 1914 },
    { number: 42, title: "Shuren", part: "Parte IV", file: "42-shuren.mp3", seconds: 1729 }
  ]
};
